# Utiliser une image de base Python avec TensorFlow
FROM tensorflow/tensorflow:2.6.0

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

COPY . /app

# Installer les dépendances du système
RUN apt-get update && apt-get install -y libsndfile1

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements3.txt


# Commande par défaut pour lancer le service VGG
CMD ["python", "vgg19_service.py"]



