# Utiliser une image de base Python
FROM python:3.8-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

COPY . /app

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements2.txt



# Commande par défaut pour lancer le service SVM
CMD ["python", "svm_service.py"]
