# Utiliser une image de base Python avec TensorFlow
FROM tensorflow/tensorflow:2.6.0

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier requirements.txt dans le conteneur
COPY app/requirements.txt /app/

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code de l'application dans le conteneur
COPY ../app /app/

# Commande par défaut pour lancer le service VGG
CMD ["python", "vgg_service.py"]



